// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workout.Infrastructure.Data;

#nullable disable

namespace Workout.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602204225_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Workout.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Chest",
                            Description = "A classic compound chest exercise targeting pectorals, anterior deltoids, and triceps.",
                            Name = "Barbell Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Chest",
                            Description = "An upper chest focused exercise targeting the clavicular head of the pectoralis major.",
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Chest",
                            Description = "An isolation exercise for chest definition and stretching the pectoral muscles.",
                            Name = "Cable Chest Fly"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Legs",
                            Description = "The king of lower body movements targeting quadriceps, glutes, hamstrings, and core.",
                            Name = "Barbell Back Squat"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Legs",
                            Description = "A machine-based lower body exercise prioritizing quadriceps and glutes with low spinal loading.",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Legs",
                            Description = "An isolation machine exercise for developing definition in the quadriceps.",
                            Name = "Leg Extensions"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Back",
                            Description = "A fundamental compound movement targeting the entire posterior chain, lower back, and hamstrings.",
                            Name = "Conventional Deadlift"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Back",
                            Description = "An upper body vertical pull targeting the latissimus dorsi and biceps.",
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Back",
                            Description = "A horizontal pulling movement for upper back thickness, lats, and rear deltoids.",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Shoulders",
                            Description = "A vertical pressing compound exercise for building strong shoulders, traps, and triceps.",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Shoulders",
                            Description = "An isolation exercise targeting the lateral deltoids for shoulder width.",
                            Name = "Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Arms",
                            Description = "A classic arm isolation movement targeting the biceps brachii.",
                            Name = "Barbell Bicep Curl"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Arms",
                            Description = "An isolation movement focusing on the lateral and medial heads of the triceps.",
                            Name = "Tricep Rope Pushdown"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Arms",
                            Description = "An overhead elbow extension exercise prioritizing the long head of the triceps.",
                            Name = "Incline Bench Skull Crushers"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Core",
                            Description = "An advanced abdominal movement targeting the lower rectus abdominis.",
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Core",
                            Description = "An isometric core exercise targeting the transverse abdominis and lower back.",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Cardio",
                            Description = "High intensity cardiovascular interval training engaging both upper and lower body.",
                            Name = "Assault Bike Interval"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Cardio",
                            Description = "Cardiovascular conditioning focused on running or walking.",
                            Name = "Treadmill Run"
                        });
                });

            modelBuilder.Entity("Workout.Domain.Entities.ScheduleWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("IX_ScheduleWorkouts_ScheduledDate");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("IX_ScheduleWorkouts_WorkoutId");

                    b.ToTable("scheduleWorkouts");
                });

            modelBuilder.Entity("Workout.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Workout.Domain.Entities.WorkoutComments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("IX_WorkoutComments_WorkoutId");

                    b.ToTable("workoutComments");
                });

            modelBuilder.Entity("Workout.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("workoutExercises");
                });

            modelBuilder.Entity("Workout.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_WorkoutPlans_UserId");

                    b.ToTable("workoutPlans");
                });

            modelBuilder.Entity("Workout.Domain.Entities.ScheduleWorkout", b =>
                {
                    b.HasOne("Workout.Domain.Entities.WorkoutPlan", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Workout.Domain.Entities.WorkoutComments", b =>
                {
                    b.HasOne("Workout.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Workout.Domain.Entities.WorkoutPlan", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Workout.Domain.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("Workout.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workout.Domain.Entities.WorkoutPlan", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Workout.Domain.Entities.WorkoutPlan", b =>
                {
                    b.HasOne("Workout.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workout.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
